### ISSUE TITLE
Using dataset

### ISSUE THREAD

**Issue by woecifaun** [lililillilil/shock#1]
On line https://github.com/lililillilil/shock/blob/master/src/view/index.html#L44

I would rather use the dataset property
```javascript
const command = event.currentTarget.dataset.command;
```

Is there any particular reason why you use the `getAttribute` function here?

**Comment by Tom32i** [comment]
Sounds good! 👍 Je te laisse corriger ? :)

**Comment by woecifaun** [comment]
fixed by https://github.com/lililillilil/shock/pull/3
